module.exports = {
  "Street": {
    "Street search": {
      "1": "\n                    \n<form action=\"/ui-street/page1\" autocomplete=\"on\" enctype=\"multipart/form-data\" method=\"post\" novalidate=\"novalidate\">\n<div class=\"govuk-form-group \">\n\n            <h1 class=\"govuk-label-wrapper\">\n            <label class=\"govuk-label govuk-label--l\" for=\"street\">\n                What street are you asking about?\n            </label>\n        </h1>\n\n\n    \n    <div class=\"govuk-inset-text\">\n        It must be a Stockport street name.\n    </div>\n\n\n    \n\n    \n\n    <input class=\"govuk-input govuk-input--width-20 \" id=\"street\" maxlength=\"200\" name=\"street\" type=\"text\" value=\"\">\n</div>\n\n<button data-prevent-double-click=\"true\" data-disable-on-click=\"true\" class=\"govuk-button \" id=\"nextStep\" data-module=\"govuk-button\">\n    Find street\n</button>\n\n<input id=\"Path\" name=\"Path\" type=\"hidden\" value=\"page1\"></form>\n                "
    },
    "Street Select": {
      "1": "\n                    \n<form action=\"/ui-street/page1/automatic\" autocomplete=\"on\" enctype=\"multipart/form-data\" method=\"post\" novalidate=\"novalidate\">\n<div class=\"govuk-form-group \">\n    <input id=\"street\" name=\"street\" type=\"hidden\" value=\"street name\">\n\n                <h1 class=\"govuk-label-wrapper\">\n            <label class=\"govuk-label govuk-label--l\" for=\"street-street\">\n                Select your street\n            </label>\n        </h1>\n\n        <p class=\"smbc-body\">\n    <strong class=\"govuk-!-margin-right-1\">Street:</strong>\n    street name\n    <a class=\"govuk-!-margin-left-6 govuk-link\" href=\"/ui-street/page1\">Change</a>\n</p>\n\n    \n\n    \n\n    <select class=\"govuk-select\" id=\"street-street\" name=\"street-street\"><option value=\"\">3 streets found</option>\n<option value=\"123456789012|Green lane\">Green lane</option>\n<option value=\"098765432109|Green road\">Green road</option>\n<option value=\"564737838937|Green street\">Green street</option>\n</select>\n</div>\n\n<button data-prevent-double-click=\"true\" class=\"govuk-button \" id=\"nextStep\" data-module=\"govuk-button\">\n    Next step\n</button>\n\n<input id=\"Path\" name=\"Path\" type=\"hidden\" value=\"page1\"></form>\n                ",
      "2": "\n                    \n<form action=\"/ui-street/page1/automatic\" autocomplete=\"on\" enctype=\"multipart/form-data\" method=\"post\" novalidate=\"novalidate\">\n<div class=\"govuk-form-group \">\n    <input id=\"street\" name=\"street\" type=\"hidden\" value=\"nodata\">\n\n                <h1 class=\"govuk-label-wrapper\">\n            <label class=\"govuk-label govuk-label--l\" for=\"street-street\">\n                Select your street\n            </label>\n        </h1>\n\n        <p class=\"smbc-body\">\n    <strong class=\"govuk-!-margin-right-1\">Street:</strong>\n    nodata\n    <a class=\"govuk-!-margin-left-6 govuk-link\" href=\"/ui-street/page1\">Change</a>\n</p>\n\n    \n\n    \n\n    <select class=\"govuk-select\" id=\"street-street\" name=\"street-street\"><option value=\"\">0 streets found</option>\n</select>\n</div>\n\n<button data-prevent-double-click=\"true\" class=\"govuk-button \" id=\"nextStep\" data-module=\"govuk-button\">\n    Next step\n</button>\n\n<input id=\"Path\" name=\"Path\" type=\"hidden\" value=\"page1\"></form>\n                "
    }
  },
  "__version": "5.4.0"
}
