module.exports = {
  "Radio": {
    "snapshot test": {
      "1": "\n    <fieldset aria-describedby=\"radButton-hint\" class=\"govuk-fieldset\">\n\n        <legend class=\"govuk-fieldset__legend govuk-fieldset__legend--m\">\n        Do you like things?\n    </legend>\n\n\n    \n\n\n        <span class=\"govuk-hint\" id=\"radButton-hint\">Things like this and that</span>\n\n\n    \n\n    \n<div class=\"govuk-radios\" data-module=\"govuk-radios\">\n        <div class=\"govuk-radios__item\">\n            <input class=\"govuk-radios__input\" type=\"radio\" value=\"yes\" name=\"radButton\" id=\"radButton-0\" aria-describedby=\"radButton-0-hint\">\n\n            <label class=\"govuk-label govuk-radios__label govuk-label--s\" for=\"radButton-0\">\n                Yes\n            </label>\n\n                <span class=\"govuk-hint govuk-radios__hint\" id=\"radButton-0-hint\"><strong>This</strong> is an affirmative response.</span>\n\n        </div>\n        <div class=\"govuk-radios__item\">\n            <input class=\"govuk-radios__input\" type=\"radio\" value=\"no\" name=\"radButton\" id=\"radButton-1\" aria-describedby=\"radButton-1-hint\">\n\n            <label class=\"govuk-label govuk-radios__label govuk-label--s\" for=\"radButton-1\">\n                No\n            </label>\n\n                <span class=\"govuk-hint govuk-radios__hint\" id=\"radButton-1-hint\">This is a negative response.</span>\n\n        </div>\n</div>\n\n    </fieldset>\n"
    },
    "snapshot conditional test": {
      "1": "\n    <fieldset class=\"govuk-fieldset\">\n\n        <legend class=\"govuk-fieldset__legend govuk-fieldset__legend--l\">\n        <h1 class=\"govuk-fieldset__heading\">\n            Select the evidence you want to use\n\n        </h1>\n    </legend>\n\n\n    \n\n\n    \n\n    \n\n    \n<div class=\"govuk-radios govuk-radios--conditional\" data-module=\"govuk-radios\">\n        <div class=\"govuk-radios__item\">\n            <input class=\"govuk-radios__input\" type=\"radio\" value=\"Option one\" name=\"conditonalRadio\" id=\"conditonalRadio-0\" aria-controls=\"conditional-0\" aria-expanded=\"false\">\n\n            <label class=\"govuk-label govuk-radios__label\" for=\"conditonalRadio-0\">\n                Option one\n            </label>\n\n\n        </div>\n            <div class=\"govuk-radios__conditional govuk-radios__conditional--hidden\" id=\"conditional-0\">\n                \n<div class=\"govuk-form-group \">\n\n            <label class=\"govuk-label govuk-label--m\" for=\"conditonalTextboxOne\">\n            Enter why you chose option one\n        </label>\n\n\n    \n\n\n    \n\n    \n\n    <input class=\"govuk-input\" id=\"conditonalTextboxOne\" maxlength=\"200\" name=\"conditonalTextboxOne\" spellcheck=\"true\" type=\"text\" value=\"\">\n</div>\n            </div>\n        <div class=\"govuk-radios__item\">\n            <input class=\"govuk-radios__input\" type=\"radio\" value=\"Option two\" name=\"conditonalRadio\" id=\"conditonalRadio-1\" aria-controls=\"conditional-1\" aria-expanded=\"false\">\n\n            <label class=\"govuk-label govuk-radios__label\" for=\"conditonalRadio-1\">\n                Option two\n            </label>\n\n\n        </div>\n            <div class=\"govuk-radios__conditional govuk-radios__conditional--hidden\" id=\"conditional-1\">\n                \n<div class=\"govuk-form-group \">\n\n            <label class=\"govuk-label govuk-label--m\" for=\"conditonalTextboxTwo\">\n            Enter why you chose option two\n        </label>\n\n\n    \n\n\n    \n\n    \n\n    <input class=\"govuk-input\" id=\"conditonalTextboxTwo\" maxlength=\"200\" name=\"conditonalTextboxTwo\" spellcheck=\"true\" type=\"text\" value=\"\">\n</div>\n            </div>\n</div>\n\n    </fieldset>\n"
    }
  },
  "__version": "6.1.0"
}
