using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using form_builder.Enum;
using form_builder.Helpers.ElementHelpers;
using form_builder.Helpers.ViewRender;
using form_builder.Models.Properties.ElementProperties;
using form_builder.ViewModels;
using Microsoft.AspNetCore.Hosting;

namespace form_builder.Models.Elements
{
    public class Summary : Element
    {
        public Summary()
        {
            Type = EElementType.Summary;
        }

        public override async Task<string> RenderAsync(IViewRender viewRender,
            IElementHelper elementHelper,
            string guid,
            Dictionary<string, dynamic> viewModel,
            Page page,
            FormSchema formSchema,
            IWebHostEnvironment environment,
            FormAnswers formAnswers,
            List<object> results = null)
        {
            var pages = elementHelper.GenerateQuestionAndAnswersList(guid, formSchema);

            if (formSchema.Pages.Any(_ => _.Elements.Any(_ => _.Type == EElementType.AddAnother)) && !Properties.HasSummarySectionsDefined)
            {
                var summaryViewModel = AutoGenerateSummarySectionsViewModel(formSchema, formAnswers, pages, elementHelper);

                return await viewRender.RenderAsync(Type.ToString(), summaryViewModel);
            }
            
            if (Properties.HasSummarySectionsDefined && !Properties.SummarySectionsAutoGenerated)
            {
                var summaryViewModel = GenerateDefinedSummarySectionViewModel(formSchema, formAnswers, pages, elementHelper);

                return await viewRender.RenderAsync(Type.ToString(), summaryViewModel);
            }

            var summaryViewModelSingleSection = new SummarySectionsViewModel
            {
                AllowEditing = Properties.AllowEditing,
                Sections = new List<SummarySection>
                    {
                        new SummarySection {
                            Pages = pages
                    }
                }
            };

            return await viewRender.RenderAsync(Type.ToString(), summaryViewModelSingleSection);
        }

        private SummarySectionsViewModel AutoGenerateSummarySectionsViewModel(FormSchema formSchema, FormAnswers formAnswers, IEnumerable<PageSummary> pages, IElementHelper elementHelper)
        {
            Properties.SummarySectionsAutoGenerated = true;
            Properties.Sections = new List<Section>();
            var groupedPageSlugs = new List<List<string>>();
            var temporarySlugGroup = new List<string>();
            foreach (var schemaPage in formSchema.Pages)
            {
                if (schemaPage.Elements.Any(_ => _.Type == EElementType.AddAnother))
                {
                    temporarySlugGroup.Add(schemaPage.PageSlug);
                    groupedPageSlugs.Add(temporarySlugGroup);
                    temporarySlugGroup = new List<string>();
                    groupedPageSlugs.Add(new List<string> { $"{schemaPage.PageSlug}-{schemaPage.Elements.FirstOrDefault(_ => _.Type == EElementType.AddAnother).Properties.QuestionId}" });
                }
                else
                {
                    temporarySlugGroup.Add(schemaPage.PageSlug);
                }
            }

            groupedPageSlugs.Add(temporarySlugGroup);

            foreach (var pageSlugGroup in groupedPageSlugs)
            {
                Properties.Sections.Add(new Section
                {
                    Pages = pageSlugGroup
                });
            }

            var addAnotherElements = formSchema.Pages
                .Where(_ => _.Elements.Any(_ => _.Type == EElementType.AddAnother))
                .SelectMany(_ => _.Elements.Where(_ => _.Type == EElementType.AddAnother)).ToList();

            foreach (var element in addAnotherElements)
            {
                var formDataIncrementKey = $"addAnotherFieldset-{element.Properties.QuestionId}";
                var currentIncrement = elementHelper.GetCurrentAddAnotherIncrement(element, formAnswers);
                var page = formSchema.Pages.FirstOrDefault(_ => _.Elements.Contains(element));
                var addAnotherSection = Properties.Sections.FirstOrDefault(_ => _.Pages.Any(_ => _.Contains($"{page.PageSlug}-{element.Properties.QuestionId}")));
                
                var indexOf = Properties.Sections.IndexOf(addAnotherSection);

                for (var i = 1; i <= currentIncrement; i++)
                {
                    Properties.Sections.Insert(indexOf + i, new Section
                    {
                        Pages = new List<string>
                            {
                                $"{page.PageSlug}-{element.Properties.QuestionId}-{i}"
                            },
                        Title = element.Properties.Label
                    });
                }

                Properties.Sections.Remove(addAnotherSection);
            }

            return new SummarySectionsViewModel
            {
                Sections = Properties.Sections.Select(_ => new SummarySection
                {
                    Title = _.Title,
                    Pages = _.Pages.SelectMany(x => pages.Where(y => y.PageSlug.Equals(x) && y.Answers.Count > 0)).ToList()
                }).ToList(),
                AllowEditing = Properties.AllowEditing
            };
        }

        private SummarySectionsViewModel GenerateDefinedSummarySectionViewModel(FormSchema formSchema, FormAnswers formAnswers, IEnumerable<PageSummary> pages, IElementHelper elementHelper)
        {
            if (formSchema.Pages.Any(_ => _.Elements.Any(_ => _.Type == EElementType.AddAnother)))
            {
                var newSections = new List<Section>();

                foreach (var section in Properties.Sections)
                {
                    foreach (var sectionPage in section.Pages)
                    {
                        newSections.Add(section);

                        var schemaPageForSection = formSchema.Pages.FirstOrDefault(_ => _.PageSlug.Equals(sectionPage));
                        if (schemaPageForSection is not null && schemaPageForSection.Elements.Any(_ => _.Type == EElementType.AddAnother))
                        {
                            var addAnotherElement = schemaPageForSection.Elements.FirstOrDefault(_ => _.Type == EElementType.AddAnother);
                            var currentIncrement = elementHelper.GetCurrentAddAnotherIncrement(addAnotherElement, formAnswers);

                            for (var i = 1; i <= currentIncrement; i++)
                            {
                                newSections.Add(new Section
                                {
                                    Pages = new List<string>
                                        {
                                            $"{schemaPageForSection.PageSlug}-{addAnotherElement.Properties.QuestionId}-{i}"
                                        },
                                    Title = addAnotherElement.Properties.Label
                                });
                            }
                        }
                    }
                }

                Properties.Sections = newSections;
            }

            return new SummarySectionsViewModel
            {
                Sections = Properties.Sections.Select(_ => new SummarySection
                {
                    Title = _.Title,
                    Pages = _.Pages.SelectMany(x => pages.Where(y => y.PageSlug.Equals(x) && y.Answers.Count > 0)).ToList()
                }).ToList(),
                AllowEditing = Properties.AllowEditing
            };
        }
    }
}