module.exports = {
  "Organisation": {
    "Organisation search": {
      "1": "\n                    \n<form action=\"/ui-organisation/page-one\" autocomplete=\"on\" enctype=\"multipart/form-data\" method=\"post\" novalidate=\"novalidate\">\n<div class=\"govuk-form-group \">\n            <h1 class=\"govuk-label-wrapper\">\n            <label class=\"govuk-label govuk-label--l\" for=\"organisation\">\n                Enter the organisation\n            </label>\n        </h1>\n\n\n        <span class=\"govuk-hint\" id=\"organisation-hint\">This is an additional hint</span>\n\n\n    \n\n    <input aria-describedby=\"organisation-hint\" autocomplete=\"organization\" class=\"govuk-input govuk-input--width-20 \" id=\"organisation\" maxlength=\"60\" name=\"organisation\" type=\"text\" value=\"\">\n</div>\n\n<button data-prevent-double-click=\"true\" data-disable-on-click=\"true\" class=\"govuk-button \" id=\"nextStep\" data-module=\"govuk-button\">\n    Find organisation\n</button>\n\n<input id=\"Path\" name=\"Path\" type=\"hidden\" value=\"page-one\"></form>\n                "
    },
    "Organisation Select": {
      "1": "\n                    \n<form action=\"/ui-organisation/page-one/automatic\" autocomplete=\"on\" enctype=\"multipart/form-data\" method=\"post\" novalidate=\"novalidate\">\n<div class=\"govuk-form-group \">\n    <input id=\"organisation\" name=\"organisation\" type=\"hidden\" value=\"org name\">\n\n                <h1 class=\"govuk-label-wrapper\">\n            <label class=\"govuk-label govuk-label--l\" for=\"organisation-organisation\">\n                Select the organisation\n            </label>\n        </h1>\n\n        <p class=\"smbc-body\">\n    <strong class=\"govuk-!-margin-right-1\">Organisation:</strong>\n    org name\n    <a class=\"govuk-!-margin-left-6 govuk-link\" href=\"/ui-organisation/page-one\">Change</a>\n</p>\n\n    \n\n    \n\n    <select class=\"govuk-select\" id=\"organisation-organisation\" name=\"organisation-organisation\"><option value=\"\">3 organisations found</option>\n<option value=\"0101010101|Organisation 1\">Organisation 1</option>\n<option value=\"0202020202|Organisation 2\">Organisation 2</option>\n<option value=\"030303030303|Organisation 3\">Organisation 3</option>\n</select>\n</div>\n\n<button data-prevent-double-click=\"true\" data-disable-on-click=\"true\" class=\"govuk-button \" id=\"nextStep\" data-module=\"govuk-button\">\n    Submit\n</button>\n\n<input id=\"Path\" name=\"Path\" type=\"hidden\" value=\"page-one\"></form>\n                ",
      "2": "\n                    \n<form action=\"/ui-organisation/page-one/automatic\" autocomplete=\"on\" enctype=\"multipart/form-data\" method=\"post\" novalidate=\"novalidate\">\n<div class=\"govuk-form-group \">\n    <input id=\"organisation\" name=\"organisation\" type=\"hidden\" value=\"nodata\">\n\n                <h1 class=\"govuk-label-wrapper\">\n            <label class=\"govuk-label govuk-label--l\" for=\"organisation-organisation\">\n                Select the organisation\n            </label>\n        </h1>\n\n        <p class=\"smbc-body\">\n    <strong class=\"govuk-!-margin-right-1\">Organisation:</strong>\n    nodata\n    <a class=\"govuk-!-margin-left-6 govuk-link\" href=\"/ui-organisation/page-one\">Change</a>\n</p>\n\n    \n\n    \n\n    <select class=\"govuk-select\" id=\"organisation-organisation\" name=\"organisation-organisation\"><option value=\"\">0 organisations found</option>\n</select>\n</div>\n\n<button data-prevent-double-click=\"true\" data-disable-on-click=\"true\" class=\"govuk-button \" id=\"nextStep\" data-module=\"govuk-button\">\n    Submit\n</button>\n\n<input id=\"Path\" name=\"Path\" type=\"hidden\" value=\"page-one\"></form>\n                "
    }
  },
  "__version": "5.4.0"
}
