module.exports = {
  "Address": {
    "Address search": {
      "1": "\n            <div class=\"govuk-grid-row\">\n                <div class=\"govuk-grid-column-two-thirds\">\n                    \n<form action=\"/ui-address/page1\" autocomplete=\"on\" enctype=\"multipart/form-data\" method=\"post\" novalidate=\"novalidate\"><h1 class=\"govuk-heading-l\">What is your home address?</h1>\n<div class=\"govuk-form-group \">\n\n            <label class=\"govuk-label govuk-label--m\" for=\"address-postcode\">\n            Enter your postcode\n        </label>\n\n\n    \n\n    \n\n    <input autocomplete=\"postal-code\" class=\"govuk-input govuk-input--width-10 \" id=\"address-postcode\" maxlength=\"60\" name=\"address-postcode\" type=\"text\" value=\"\">\n</div>\n\n<button data-prevent-double-click=\"true\" data-disable-on-click=\"true\" class=\"govuk-button \" id=\"nextStep\" data-module=\"govuk-button\">\n    Find address\n</button>\n\n<input id=\"Path\" name=\"Path\" type=\"hidden\" value=\"page1\"></form>\n                </div>\n            </div>\n        "
    },
    "Address Select": {
      "1": "\n            <div class=\"govuk-grid-row\">\n                <div class=\"govuk-grid-column-two-thirds\">\n                    \n<form action=\"/ui-address/page1/automatic\" autocomplete=\"on\" enctype=\"multipart/form-data\" method=\"post\" novalidate=\"novalidate\"><h1 class=\"govuk-heading-l\">What is your home address?</h1>\n<div class=\"govuk-form-group \">\n    <input id=\"address-postcode\" name=\"address-postcode\" type=\"hidden\" value=\"sk11aa\">\n\n        <p class=\"smbc-body\">\n    <strong class=\"govuk-!-margin-right-1\">Postcode:</strong>\n    sk11aa\n    <a class=\"govuk-!-margin-left-6 govuk-link\" href=\"/ui-address/page1\">Change</a>\n</p>\n                <label class=\"govuk-label govuk-label--m\" for=\"address-address\">\n            Select an address\n        </label>\n\n\n    \n    \n\n    <select class=\"govuk-select\" id=\"address-address\" name=\"address-address\"><option value=\"\">3 addresses found</option>\n<option value=\"123456789012|address 1\">address 1</option>\n<option value=\"098765432109|address 2\">address 2</option>\n<option value=\"564737838937|address 3\">address 3</option>\n</select>\n\n        <p class=\"smbc-body govuk-link govuk-!-margin-top-5\">\n            <a class=\"govuk-link\" href=\"/ui-address/page1/manual\">I can't find my address in the list</a>\n        </p>\n</div>\n\n<button data-prevent-double-click=\"true\" class=\"govuk-button \" id=\"nextStep\" data-module=\"govuk-button\">\n    Continue\n</button>\n\n<input id=\"Path\" name=\"Path\" type=\"hidden\" value=\"page1\"></form>\n                </div>\n            </div>\n        "
    },
    "Address Manual": {
      "1": "\n            <div class=\"govuk-grid-row\">\n                <div class=\"govuk-grid-column-two-thirds\">\n                    \n<form action=\"/ui-address/page1/manual\" autocomplete=\"on\" enctype=\"multipart/form-data\" method=\"post\" novalidate=\"novalidate\"><h1 class=\"govuk-heading-l\">What is your home address?</h1>\n<input id=\"address-postcode\" name=\"address-postcode\" type=\"hidden\" value=\"sk11zz\">\n\n<fieldset class=\"govuk-fieldset\">\n        <legend class=\"govuk-fieldset__legend govuk-fieldset__legend--m\">\n        Enter an address\n    </legend>\n\n\n    <p class=\"smbc-body\">\n    <strong class=\"govuk-!-margin-right-1\">Postcode:</strong>\n    sk11zz\n    <a class=\"govuk-!-margin-left-6 govuk-link\" href=\"/ui-address/page1\">Change</a>\n</p>\n\n        \n    <div class=\"govuk-inset-text\">\n        No address found at the postcode. Enter your address manually.\n    </div>\n\n\n\n    <div class=\"govuk-form-group \">\n        <label class=\"govuk-label govuk-label--m\" for=\"address-AddressLine1\">Address line 1</label>\n        \n        <input autocomplete=\"address-line1\" class=\"govuk-input\" id=\"address-AddressLine1\" name=\"address-AddressLine1\" type=\"text\" value=\"\">\n    </div>\n\n    <div class=\"govuk-form-group\">\n        <label class=\"govuk-label govuk-label--m\" for=\"address-AddressLine2\">\n            Address line 2\n            <span class=\"smbc-body\">(optional)</span>\n        </label>\n        <input autocomplete=\"address-line2\" class=\"govuk-input\" id=\"address-AddressLine2\" name=\"address-AddressLine2\" type=\"text\" value=\"\">\n    </div>\n\n    <div class=\"govuk-form-group \">\n        <label class=\"govuk-label govuk-label--m\" for=\"address-AddressTown\">Town or city</label>\n        \n        <input autocomplete=\"address-level1\" class=\"govuk-input govuk-!-width-two-thirds\" id=\"address-AddressTown\" name=\"address-AddressTown\" type=\"text\" value=\"\">\n    </div>\n\n    <div class=\"govuk-form-group \">\n        <label class=\"govuk-label govuk-label--m\" for=\"address-ManualPostcode\">Postcode</label>\n        \n\n        <input autocomplete=\"postal-code\" class=\"govuk-input govuk-input--width-10\" id=\"address-ManualPostcode\" name=\"address-ManualPostcode\" type=\"text\" value=\"sk11zz\">\n    </div>\n</fieldset>\n\n<button data-prevent-double-click=\"true\" class=\"govuk-button \" id=\"nextStep\" data-module=\"govuk-button\">\n    Continue\n</button>\n\n<input id=\"Path\" name=\"Path\" type=\"hidden\" value=\"page1\"></form>\n                </div>\n            </div>\n        "
    }
  },
  "__version": "3.8.3"
}
