name: .NET Core

on:
  push:
    branches: 
      - master
      - design-system
  pull_request:
    branches:
      - master
      - design-system

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '2.2.207'
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test ./tests/form-builder-tests-unit.csproj
